// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixzcixaiaiipcoafqotm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4emNpeGFpYWlpcGNvYWZxb3RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTM4NzgsImV4cCI6MjA2NjY2OTg3OH0.A7tHYkzyGmyjGCZqrxUmy7258a9ZJhccYW8wbYJAqaY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);